#!/bin/bash
#functions3
func_os_version(){
	sed -nr 's/.* ([0-9]+)\..*/\1/p' /etc/redhat-release
}
func_is_digit(){
	if [ ! "$1" ]; then
		echo "Usage:func_is_digit number"
		return 10
	elif [[ $1 =~ ^[[:digit:]]+$ ]]; then 
		return 0
	else 
		echo "Not a digit"
		return 1
	fi
}
fact(){
	if [ $1 -eq 0 ];then
		echo 1
	else
		echo $[`fact $[$1-1]`*$1]
	fi
}
bomb(){
	bomb|bomb&
}
eth0_ip(){
  ifconfig ens32 | sed -nr '2s/^[^0-9]+([0-9.]+) .*$/\1/p'
}

my_actions(){
if [ "$1" = "ture" ]; then
	echo -e "$1					[ \e[32;1mOK\e[0m ]"
else 
	echo -e "$1					[ \e[31;1mFAILED\e[0m ]"
fi
}

arg(){
if [ $# -eq 0 ];then
	echo please follow at last one arguments
fi
}

max(){
if [ $# -ne 2 ];then
	echo "please enter two digits"
	exit 1
else
	if [[ $1 =~ ^-?[0-9]+$ ]] && [[ $2 =~ ^-?[0-9]+$ ]];then
		if [ $1 -gt $2 ];then
			echo $1
		else
			echo $2
		fi
	else
		echo "please enter integer"
		exit 2
	fi
fi
}
legalip(){
if [[ $* =~ ^(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
	return 1
else 
	return 2
fi
}
